name: Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2

      -
        name: Setup Node.js environment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 17.x

      -
        name: Install dependencies
        run: yarn

      -
        name: Build documentation
        run: yarn run build-docs

      -
        name: Deploy
        uses: s0/git-publish-subdir-action@master
        env:
          REPO: git@github.com:Cloudstek/scim-filter-parser-docs.git
          BRANCH: master
          FOLDER: _docpress
          SSH_PRIVATE_KEY: ${{ secrets.DOCS_PRIVATE_KEY }}
